# Generated by Django 4.2.2 on 2024-11-07 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_deactivate_mailing', 'Can deactivate mailing')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='mailingattempt',
            options={'verbose_name': 'Попытка', 'verbose_name_plural': 'Попытки'},
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(to='mailing.client', verbose_name='клиенты'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailingattempt',
            name='send_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время отправки'),
        ),
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='e-mail адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Ф.И.О клиента'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата завершения рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='сообщение'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='periodicity',
            field=models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], max_length=10, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(auto_now=True, verbose_name='дата начала рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('started', 'Активна'), ('completed', 'Завершена'), ('disabled', 'Отключить')], default='created', max_length=10, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='server_response',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ почтового сервера'),
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='status',
            field=models.CharField(choices=[('success', 'Успешно'), ('failed', 'Не успешно')], max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Тема сообщения'),
        ),
    ]
